In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings 
warnings.filterwarnings("ignore", category=FutureWarning, module="seaborn")

# EDA and Things

In [2]:
df_raw = pd.read_csv("/kaggle/input/playground-series-s5e3/train.csv")

In [3]:
df_raw.head()

,id,day,pressure,maxtemp,temparature,mintemp,dewpoint,humidity,cloud,sunshine,winddirection,windspeed,rainfall
0,0,1,1017.4,21.2,20.6,19.9,19.4,87.0,88.0,1.1,60.0,17.2,1
1,1,2,1019.5,16.2,16.9,15.8,15.4,95.0,91.0,0.0,50.0,21.9,1
2,2,3,1024.1,19.4,16.1,14.6,9.3,75.0,47.0,8.3,70.0,18.1,1
3,3,4,1013.4,18.1,17.8,16.9,16.8,95.0,95.0,0.0,60.0,35.6,1
4,4,5,1021.8,21.3,18.4,15.2,9.6,52.0,45.0,3.6,40.0,24.8,0

In [4]:
df_raw.describe()

,id,day,pressure,maxtemp,temparature,mintemp,dewpoint,humidity,cloud,sunshine,winddirection,windspeed,rainfall
count,2190.000000,2190.000000,2190.000000,2190.000000,2190.000000,2190.000000,2190.000000,2190.000000,2190.000000,2190.000000,2190.000000,2190.000000,2190.000000
mean,1094.500000,179.948402,1013.602146,26.365799,23.953059,22.170091,20.454566,82.036530,75.721918,3.744429,104.863151,21.804703,0.753425
std,632.342866,105.203592,5.655366,5.654330,5.222410,5.059120,5.288406,7.800654,18.026498,3.626327,80.002416,9.898659,0.431116
min,0.000000,1.000000,999.000000,10.400000,7.400000,4.000000,-0.300000,39.000000,2.000000,0.000000,10.000000,4.400000,0.000000
25%,547.250000,89.000000,1008.600000,21.300000,19.300000,17.700000,16.800000,77.000000,69.000000,0.400000,40.000000,14.125000,1.000000
50%,1094.500000,178.500000,1013.000000,27.800000,25.500000,23.850000,22.150000,82.000000,83.000000,2.400000,70.000000,20.500000,1.000000
75%,1641.750000,270.000000,1017.775000,31.200000,28.400000,26.400000,25.000000,88.000000,88.000000,6.800000,200.000000,27.900000,1.000000
max,2189.000000,365.000000,1034.600000,36.000000,31.500000,29.800000,26.700000,98.000000,100.000000,12.100000,300.000000,59.500000,1.000000

In [5]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2190 entries, 0 to 2189
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             2190 non-null   int64
 1   day            2190 non-null   int64
 2   pressure       2190 non-null   float64
 3   maxtemp        2190 non-null   float64
 4   temparature    2190 non-null   float64
 5   mintemp        2190 non-null   float64
 6   dewpoint       2190 non-null   float64
 7   humidity       2190 non-null   float64
 8   cloud          2190 non-null   float64
 9   sunshine       2190 non-null   float64
 10  winddirection  2190 non-null   float64
 11  windspeed      2190 non-null   float64
 12  rainfall       2190 non-null   int64
dtypes: float64(10), int64(3)
memory usage: 222.5 KB

In [6]:
df_clean = df_raw.drop(columns=["id"])

## Feature Engineering
### Things to Alter:
- Very Skewed Things (Apply Log Transformation): Literally Everything is super skewed
- Adding lots of interaction terms for testing in cross validation
- Adding interaction terms for testing in cross validation

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [8]:
features = ['pressure', 'maxtemp', 'temparature', 'mintemp', 'dewpoint',
            'humidity', 'cloud', 'sunshine', 'winddirection', 'windspeed']

In [9]:
X = df_clean.drop(columns=["rainfall"])
y = df_clean["rainfall"]
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.3, random_state=42)

In [10]:
X_train.describe()

,day,pressure,maxtemp,temparature,mintemp,dewpoint,humidity,cloud,sunshine,winddirection,windspeed
count,1533.000000,1533.000000,1533.000000,1533.000000,1533.000000,1533.000000,1533.000000,1533.000000,1533.000000,1533.000000,1533.000000
mean,181.801044,1013.731768,26.336138,23.934312,22.155121,20.417091,82.059361,75.684279,3.721918,104.188063,21.667254
std,105.415367,5.589766,5.630754,5.177435,5.000233,5.242251,7.661899,17.929969,3.604967,79.774492,9.949474
min,1.000000,999.000000,10.800000,7.400000,4.000000,-0.300000,39.000000,2.000000,0.000000,10.000000,4.400000
25%,91.000000,1008.700000,21.300000,19.400000,17.700000,16.800000,77.000000,69.000000,0.400000,40.000000,14.000000
50%,181.000000,1013.300000,27.700000,25.400000,23.700000,22.100000,82.000000,83.000000,2.400000,70.000000,20.500000
75%,274.000000,1017.800000,31.100000,28.300000,26.400000,24.900000,87.000000,88.000000,6.700000,200.000000,27.600000
max,365.000000,1034.600000,36.000000,31.500000,29.800000,26.700000,98.000000,100.000000,12.000000,300.000000,59.500000

In [11]:
def make_cool_features(df):
    df_temp = df.copy()
    # scaler = StandardScaler()
    # df_temp[features] = scaler.fit_transform(df_temp[features])

    for feature in features:
        df_temp[f"Log_{feature}"] = np.log(df_temp[feature] + 1)

    scaler = StandardScaler()
    df_temp[df_temp.drop(columns="day").columns] = scaler.fit_transform(df_temp[df_temp.drop(columns="day").columns])

    for i in range(len(features)-1):
        # polynomial terms
        df_temp[f"{features[i]}2"] = df_temp.apply(lambda x: x[features[i]]**2, axis=1)
        df_temp[f"{features[i]}3"] = df_temp.apply(lambda x: x[features[i]]**3, axis=1)
        for j in range(i+1, len(features)-1):
            # interaction term
            df_temp[f"{features[i]}_{features[j]}"] = df_temp[features[i]] * df_temp[features[j]]
    
    return df_temp

In [12]:
X_train_cool = make_cool_features(X_train)
X_val_cool = make_cool_features(X_val)

In [13]:
X_train_cool.head()

,day,pressure,maxtemp,temparature,mintemp,dewpoint,humidity,cloud,sunshine,winddirection,...,humidity_winddirection,cloud2,cloud3,cloud_sunshine,cloud_winddirection,sunshine2,sunshine3,sunshine_winddirection,winddirection2,winddirection3
576,212,-0.918364,0.988443,0.920773,0.829208,1.046249,0.514484,0.687103,-0.699796,1.577609,...,0.811655,0.472111,0.324389,-0.480832,1.083981,0.489714,-0.342700,-1.104005,2.488852,3.926436
1355,261,-0.274120,0.366653,0.572997,0.429096,0.550117,-0.399426,-1.600317,1.298100,1.703004,...,-0.680223,2.561015,-4.098437,-2.077372,-2.725346,1.685065,2.187383,2.210670,2.900222,4.939088
339,340,1.336490,-0.947987,-0.914711,-0.951290,-0.747459,-0.007750,0.687103,-0.977281,-0.679487,...,0.005266,0.472111,0.324389,-0.671493,-0.466878,0.955079,-0.933381,0.664050,0.461703,-0.313721
862,133,-0.757303,1.183862,1.191266,0.989252,1.046249,-0.921660,-0.372921,1.742077,1.452215,...,-1.338448,0.139070,-0.051862,-0.649657,-0.541561,3.034833,5.286914,2.529871,2.108929,3.062619
265,266,0.477498,0.419950,0.321826,-0.331117,0.817265,0.253367,0.687103,-0.172573,-0.303304,...,-0.076847,0.472111,0.324389,-0.118576,-0.208401,0.029782,-0.005139,0.052342,0.091994,-0.027902

# Logistic Regression Things

In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import GridSearchCV

In [15]:
# baseline model
clf0 = LogisticRegression(random_state=42, max_iter=100).fit(X_train, y_train)

# actual model
clf = LogisticRegression(penalty='l1', solver='liblinear', random_state=42, max_iter=1000)

param_grid = {'C': [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10]}

grid_search = GridSearchCV(
    clf,
    param_grid,
    cv=10,
    scoring='roc_auc'
)

grid_search.fit(X_train_cool, y_train)

best_model = grid_search.best_estimator_

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [16]:
feature_importance = pd.DataFrame({
    'Feature': X_train_cool.columns,
    'Coefficient': best_model.coef_[0]
})
selected_features = feature_importance[feature_importance['Coefficient'] != 0]['Feature']

In [17]:
print(best_model)
print(selected_features)

LogisticRegression(C=0.1, max_iter=1000, penalty='l1', random_state=42,
                   solver='liblinear')
0                        day
5                   dewpoint
6                   humidity
7                      cloud
18              Log_sunshine
20             Log_windspeed
22                 pressure3
28            pressure_cloud
30    pressure_winddirection
31                  maxtemp2
32                  maxtemp3
48                  mintemp2
57         dewpoint_humidity
61                 humidity2
68            cloud_sunshine
71                 sunshine3
Name: Feature, dtype: object

In [18]:
y_val_probs = clf0.predict_proba(X_val)[:, 1]
roc_auc = roc_auc_score(y_val, y_val_probs)
print(f"ROC AUC Score Baseline: {roc_auc:.4f}")

y_val_probs = best_model.predict_proba(X_val_cool)[:, 1]
roc_auc = roc_auc_score(y_val, y_val_probs)
print(f"ROC AUC Score Good: {roc_auc:.4f}")

ROC AUC Score Baseline: 0.8749
ROC AUC Score Good: 0.8721

# XGBoost Model

## XGBoost - Baseline

In [19]:
import xgboost as xgb
from sklearn.metrics import roc_auc_score

In [20]:
xgb_baseline = xgb.XGBClassifier(objective='binary:logistic').fit(X_train_cool, y_train)

In [21]:
y_val_probs = clf0.predict_proba(X_val)[:, 1]
roc_auc = roc_auc_score(y_val, y_val_probs)
print(f"ROC AUC Score Baseline: {roc_auc:.4f}")

y_pred_xgb_baseline = xgb_baseline.predict_proba(X_val_cool)[:, 1]
roc_auc = roc_auc_score(y_val, y_pred_xgb_baseline)
print(f"ROC AUC Score Baseline: {roc_auc:.4f}")

ROC AUC Score Baseline: 0.8749
ROC AUC Score Baseline: 0.8535

## XGBoost - Simple

In [22]:
from sklearn.model_selection import GridSearchCV

In [23]:
# xgb_model = xgb.XGBClassifier(
#     objective='binary:logitraw',
#     eval_metric='auc',
#     use_label_encoder=False,
#     verbosity=2,
#     random_state=42,
#     n_jobs=-1
#     # eval_set=[(X_train_cool, y_train)]
# )

In [24]:
# param_grid = {
#     'learning_rate': [0.01, 0.05, 0.1],
#     'max_depth': [3, 5, 7, 9],
#     'n_estimators': [100, 200, 300, 400],
#     'gamma': [0, 0.1, 0.05],
#     'min_child_weight': [1, 2, 3],
#     'lambda': [0.1, 0.5, 1],
#     'alpha': [0.1, 0.5, 1]
# }

In [25]:
# %%time

# grid_search = GridSearchCV(
#     estimator=xgb_model,
#     param_grid=param_grid,
#     scoring='roc_auc',
#     cv=5,
#     verbose=1
# )

# grid_search.fit(X_train_cool, y_train)
# best_model_grid = grid_search.best_estimator_

In [26]:
# best_params_grid = grid_search.best_params_

In [27]:
# best_params_grid

In [28]:
# y_pred_grid = best_model_grid.predict(X_val_cool)
# roc_auc = roc_auc_score(y_val, y_pred_grid)
# print(f"XGB Val Accuracy: {roc_auc:.4f}")

## XGBoost - Big Boy

In [29]:
# from hyperopt import STATUS_OK, Trials, fmin, hp, tpe

In [30]:
# space={'max_depth': hp.quniform("max_depth", 3, 25, 1),
#         'gamma': hp.uniform ('gamma', 1,9),
#         'reg_alpha' : hp.quniform('reg_alpha', 40,180,1),
#         'reg_lambda' : hp.uniform('reg_lambda', 0,1),
#         'colsample_bytree' : hp.uniform('colsample_bytree', 0.5,1),
#         'min_child_weight' : hp.quniform('min_child_weight', 0, 10, 1),
#         'n_estimators': hp.quniform("n_estimators", 100, 200, 1),
#         'learning_rate': hp.uniform("learning_rate", 0.01, 0.1),
#         'seed': 42
#     }

In [31]:
# def objective(space):
#     clf=xgb.XGBClassifier(
#                     n_estimators =int(space['n_estimators']), 
#                     max_depth = int(space['max_depth']), 
#                     gamma = space['gamma'],
#                     reg_alpha = int(space['reg_alpha']),
#                     min_child_weight=int(space['min_child_weight']),
#                     colsample_bytree=int(space['colsample_bytree']), 
#                     eval_metric="auc", 
#                     learning_rate=space['learning_rate']
#     )
    
#     evaluation = [( X_train_cool, y_train), ( X_val_cool, y_val)]
    
#     clf.fit(X_train_cool, y_train,
#             eval_set=evaluation,
#             verbose=False)
    

#     pred = clf.predict(X_val_cool)
#     accuracy = roc_auc_score(y_val, pred)
#     print ("SCORE:", accuracy)
#     return {'loss': -accuracy, 'status': STATUS_OK }

In [32]:
# trials = Trials()

# best_hyperparams = fmin(fn = objective,
#                         space = space,
#                         algo = tpe.suggest,
#                         max_evals = 1000,
#                         trials = trials)

In [33]:
# best_model_hyperopt = xgb.XGBClassifier(
#         n_estimators = int(best_hyperparams['n_estimators']), 
#         max_depth = int(best_hyperparams['max_depth']), 
#         gamma = best_hyperparams['gamma'],
#         reg_alpha = int(best_hyperparams['reg_alpha']),
#         min_child_weight = int(best_hyperparams['min_child_weight']),
#         colsample_bytree = int(best_hyperparams['colsample_bytree']), 
#         eval_metric = "auc", 
#         learning_rate = best_hyperparams['learning_rate']
#     )

# best_model_hyperopt.fit(X_train_cool, y_train)

# y_pred_hyperopt = best_model_hyperopt.predict(X_val_cool)
# roc_auc = roc_auc_score(y_val, y_pred_hyperopt)
# print(f"XGB Hyperopt Val Accuracy: {roc_auc:.4f}")

### What did we learn:
we learned that the baseline logistic regression model is really really hard to beat holy wtf.

## Submission

In [34]:
X_cool = make_cool_features(X)

In [35]:
df_test = pd.read_csv("/kaggle/input/playground-series-s5e3/test.csv")

In [36]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             730 non-null    int64
 1   day            730 non-null    int64
 2   pressure       730 non-null    float64
 3   maxtemp        730 non-null    float64
 4   temparature    730 non-null    float64
 5   mintemp        730 non-null    float64
 6   dewpoint       730 non-null    float64
 7   humidity       730 non-null    float64
 8   cloud          730 non-null    float64
 9   sunshine       730 non-null    float64
 10  winddirection  729 non-null    float64
 11  windspeed      730 non-null    float64
dtypes: float64(10), int64(2)
memory usage: 68.6 KB

In [37]:
df_test.describe()

,id,day,pressure,maxtemp,temparature,mintemp,dewpoint,humidity,cloud,sunshine,winddirection,windspeed
count,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,729.000000,730.000000
mean,2554.500000,183.000000,1013.503014,26.372466,23.963288,22.110274,20.460137,82.669863,76.360274,3.664384,103.923182,22.484247
std,210.877136,105.438271,5.505871,5.672521,5.278098,5.170744,5.391169,7.818714,17.934121,3.639272,81.695458,9.954779
min,2190.000000,1.000000,1000.000000,7.400000,5.900000,4.200000,-0.000000,39.000000,0.000000,0.000000,10.000000,4.500000
25%,2372.250000,92.000000,1008.725000,21.600000,19.825000,17.825000,16.800000,77.250000,69.000000,0.325000,40.000000,14.500000
50%,2554.500000,183.000000,1012.700000,27.800000,25.650000,23.900000,22.300000,82.000000,83.000000,2.200000,70.000000,21.300000
75%,2736.750000,274.000000,1017.600000,31.000000,28.375000,26.400000,25.000000,89.000000,88.000000,6.675000,200.000000,28.400000
max,2919.000000,365.000000,1032.200000,35.800000,31.800000,29.100000,26.700000,98.000000,100.000000,11.800000,300.000000,59.500000

In [38]:
df_test = df_test.fillna(0)
scaler_test = StandardScaler()
df_test_cool = make_cool_features(df_test)

In [39]:
best_model = xgb.XGBClassifier(
    objective='binary:logitraw',
    eval_metric='auc',
    use_label_encoder=False,
    random_state=42,
    gamma = 0,
    learning_rate = 0.01,
    max_depth = 3,
    min_child_weight = 5,
    n_estimators = 200
)
best_model.fit(X_cool, y)
# best_model_grid.fit(X_cool, y)

y_pred_xgb = best_model.predict_proba(X_val_cool)[:, 1]
roc_auc = roc_auc_score(y_val, y_pred_xgb)
print(f"XGB Val Accuracy: {roc_auc:.4f}")

XGB Val Accuracy: 0.8911

In [40]:
y_pred = best_model.predict_proba(df_test_cool.drop(columns=["id"]))[:, 1]
df_test['rainfall'] = y_pred

In [41]:
# y_pred = best_model.predict_proba(df_test_cool.drop(columns=["id"]))[:, 1]
# df_test["rainfall"] = y_pred
# df_test.head()

In [42]:
submission = df_test[["id", "rainfall"]]
submission.to_csv("submission.csv", index=False)
submission.head()

     id  rainfall
0  2190  2.704040
1  2191  2.738318
2  2192  2.152528
3  2193 -1.152124
4  2194 -1.310573