In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings 
warnings.simplefilter("ignore")

### How handle Missing
- Encoding episode_length as 40 to make it more represnetative of actual distribution since kind of a skew exists
- Try with some log transformations

# EDA

In [2]:
df = pd.read_csv("/kaggle/input/playground-series-s5e4/train.csv")
df.head()

,id,Podcast_Name,Episode_Title,Episode_Length_minutes,Genre,Host_Popularity_percentage,Publication_Day,Publication_Time,Guest_Popularity_percentage,Number_of_Ads,Episode_Sentiment,Listening_Time_minutes
0,0,Mystery Matters,Episode 98,NaN,True Crime,74.81,Thursday,Night,NaN,0.0,Positive,31.41998
1,1,Joke Junction,Episode 26,119.80,Comedy,66.95,Saturday,Afternoon,75.95,2.0,Negative,88.01241
2,2,Study Sessions,Episode 16,73.90,Education,69.97,Tuesday,Evening,8.97,0.0,Negative,44.92531
3,3,Digital Digest,Episode 45,67.17,Technology,57.22,Monday,Morning,78.70,2.0,Positive,46.27824
4,4,Mind & Body,Episode 86,110.51,Health,80.07,Monday,Afternoon,58.68,3.0,Neutral,75.61031

# Feature Engineering

### Transformations to Apply
#### Variable Specific Transformations
- Turning episode title into discrete numeric variable for the episode number
  
#### Numeric  
- Standardization
- Box-Cox Transformation for every numeric variable for funsies
  
#### Categorical  
- One hot encodings
  
#### Numeric and Categorical  
- Interaction Terms Between Every single variable, just for funsies

In [3]:
# # data cleaning
# def replace_episode_length(df):
#     df_temp = df.copy()

#     df_temp["Episode_Length_missing"] = pd.isna(df_temp["Episode_Length_minutes"])
#     df_temp.loc[df_temp["Episode_Length_minutes"].isna(), "Episode_Length_minutes"] = df_temp["Episode_Length_minutes"].median()
#     return df_temp

# def replace_guest_popularity(df):
#     df_temp = df.copy()

#     df_temp["Guest_Popularity_percentage"] = pd.isna(df_temp["Guest_Popularity_percentage"])
#     df_temp.loc[df_temp["Guest_Popularity_percentage"].isna(), "Guest_Popularity_percentage"] = df_temp["Guest_Popularity_percentage"].median()
#     return df_temp

# def replace_num_ads(df):
#     df_temp = df.copy()

#     df_temp["Number_of_Ads"] = pd.isna(df_temp["Number_of_Ads"])
#     df_temp.loc[df_temp["Number_of_Ads"].isna(), "Number_of_Ads"] = 0
#     return df_temp

# def replace_outliers(df):
#     df_temp = df.copy()

#     df_temp.loc[df_temp["Episode_Length_minutes"] > 300, "Episode_Length_minutes"] = 120
#     df_temp.loc[df_temp["Number_of_Ads"] > 10, "Number_of_Ads"] = 10
#     df_temp.loc[df_temp["Host_Popularity_percentage"] < 20] = 20
#     df_temp.loc[df_temp["Host_Popularity_percentage"] > 100] = 100
#     df_temp.loc[df_temp["Guest_Popularity_percentage"] > 100] = 100
    
#     return df_temp

# def clean_data(df):
#     df_temp = df.copy()
#     df_temp = df_temp.drop(columns=["id"])

#     # replacing outliers with max/min
#     df_temp = replace_outliers(df_temp)
#     df_temp = replace_guest_popularity(df_temp)
#     df_temp = replace_episode_length(df_temp)
#     df_temp = replace_num_ads(df_temp)

#     df_temp["Episode_Title"] = df_temp.apply(lambda x: x["Episode_Title"] if not str(x["Episode_Title"]).isdigit() else "Episode " + str(x["Episode_Title"]), axis=1)
    
#     return df_temp

In [4]:
from sklearn.preprocessing import StandardScaler

num_features = ["Episode_Length_minutes", "Host_Popularity_percentage", "Guest_Popularity_percentage", 
                "Number_of_Ads"] # Removed Outcome var

# numerical features actually transformed
num_features_transform = ["Episode_Length_minutes", "Host_Popularity_percentage", "Guest_Popularity_percentage"]

cat_features = ["Podcast_Name", "Genre", "Publication_Day", "Publication_Time", 
                "Episode_Sentiment"] # Episode Title removed since its now int

# This thing not used
features = ["Episode_Length_minutes", "Host_Popularity_percentage", "Guest_Popularity_percentage", 
            "Number_of_Ads", "episode_number", "Podcast_Name", "Genre", "Publication_Day", 
            "Publication_Time", "Episode_Sentiment", "Episode_Length_missing"]

def make_cool_features(df):
    df_temp = df.copy()

    # Apply the function to create new column for episode number
    df_temp['episode_number'] = df_temp['Episode_Title'].str.extract(r'Episode (\d+)').astype(int)
    df_temp = df_temp.drop(columns=["Episode_Title"])

    # standardizationfor numerical features
    scaler = StandardScaler()
    df_temp[num_features_transform] = scaler.fit_transform(df_temp[num_features_transform])

    # need this thing
    df_temp1 = df_temp.copy()

    # encoding categorical features
    df_temp = pd.get_dummies(df_temp, columns=cat_features)

    # log transformations
    for feature in num_features_transform:
        if (df_temp[feature] <= 0).any():
            shift_value = abs(df_temp[feature].min()) + 1
            df_temp[f'{feature}_log'] = np.log(df_temp[feature] + shift_value)
        else:
            df_temp[f'{feature}_log'] = np.log(df_temp[feature])

    # ah
    if "Listening_Time_minutes" in df_temp.columns:
        numerical_columns = df_temp.drop(columns=["Listening_Time_minutes"]).select_dtypes(include=['int64', 'float64']).columns
    else:
        numerical_columns = df_temp.select_dtypes(include=['int64', 'float64']).columns
    categorical_columns = df_temp.select_dtypes(include=['object', 'bool']).columns.tolist()

    # interaction temrs
    # interaction terms between numeric and cat
    # for num_feat in numerical_columns:
    #     for cat_feat in categorical_columns:
    #         # interaction term
    #         df_temp[f"{num_feat}_{cat_feat}"] = df_temp[num_feat] * df_temp[cat_feat]

    # interaction terms between all numeric
    for i in range(len(numerical_columns) - 1):
        for j in range(i+1, len(numerical_columns)):
            df_temp[f"{numerical_columns[i]}_{numerical_columns[j]}"] = df_temp[numerical_columns[i]] * df_temp[numerical_columns[j]]

    continuous_num = ["Episode_Length_minutes", "Host_Popularity_percentage", "Guest_Popularity_percentage"]
    everything_else = ['Podcast_Name', 'Genre', 'Publication_Day', 'Publication_Time', 'Number_of_Ads', 'Episode_Sentiment', "episode_number"]

    # funky term
    # featureX - Groupby(featureY)[featureX].mean()
    for feat_X in continuous_num:
        for feat_y in everything_else:
            df_temp[f"cool_{feat_X}_{feat_y}"] = df_temp1[feat_X] - df_temp1.groupby(feat_y)[feat_X].transform('mean')
            
    
    return df_temp

In [5]:
%%time
# df_cool = clean_data(df)
df_cool = make_cool_features(df)
all_features = df_cool.drop(columns=["Listening_Time_minutes"]).columns
df_cool.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 750000 entries, 0 to 749999
Columns: 139 entries, id to cool_Guest_Popularity_percentage_episode_number
dtypes: bool(72), float64(64), int64(3)
memory usage: 434.9 MB
CPU times: user 3.25 s, sys: 448 ms, total: 3.7 s
Wall time: 3.65 s

# Model Building

In [6]:
# imports
import xgboost as xgb
from sklearn.metrics import mean_squared_error
from sklearn.metrics import make_scorer

In [7]:
from sklearn.model_selection import train_test_split
df_baseline = df.copy()
df_baseline[df_baseline.select_dtypes(include='object').columns] = df_baseline[df_baseline.select_dtypes(include='object').columns].astype('category')

X = df_baseline.drop(columns=['Listening_Time_minutes'])
y = df_baseline['Listening_Time_minutes']
X_train, X_val, y_train, y_val = train_test_split(df_baseline.drop(columns=['Listening_Time_minutes']), df_baseline["Listening_Time_minutes"], test_size = 0.3, random_state = 16)

In [8]:
def rmse_loss(y_pred, y_actual):
    return np.sqrt(mean_squared_error(y_pred, y_actual))

rmse = make_scorer(rmse_loss, greater_is_better=False)

In [9]:
%%time
xgb_baseline = xgb.XGBRegressor(enable_categorical=True).fit(X_train, y_train)

y_pred = xgb_baseline.predict(X_val)
cool_score = rmse_loss(y_pred, y_val)
print(f"Baseline RMSE: {cool_score}")

Baseline RMSE: 13.100228571419084
CPU times: user 26.5 s, sys: 69.9 ms, total: 26.6 s
Wall time: 6.84 s

## Feature Selection

In [10]:
# # PCA
# from sklearn.decomposition import PCA

# pca = PCA()
# df_cool_values = df_cool.drop(columns=["Listening_Time_minutes"]).dropna().values
# pca.fit(df_cool_values)
# cumulative_explained_variance = np.cumsum(pca.explained_variance_ratio_)
# n_components = np.argmax(cumulative_explained_variance >= 0.95) + 1
# pca = PCA(n_components=n_components)
# pca_reduced = pca.fit_transform(df_cool_values)

In [11]:
# from sklearn.feature_selection import SequentialFeatureSelector

In [12]:
# %%time
X = df_cool.drop(columns=["Listening_Time_minutes"])
y = df_cool["Listening_Time_minutes"]
# xgb_unfitted = xgb.XGBRegressor()
# sfs = SequentialFeatureSelector(xgb_unfitted, scoring=rmse, n_features_to_select='auto', tol=0.5)
# sfs.fit(X, y)
# selected_features = sfs.get_feature_names_out()
# print(f"Selected Features: {selected_features}")

In [13]:
# df_cool_selected = df_cool[selected_features]

# X_train, X_val, y_train, y_val = train_test_split(df_cool[selected_features], df_cool["Listening_Time_minutes"], test_size=0.3, random_state=16)

# xgb_1 = xgb.XGBRegressor().fit(X_train, y_train)

# y_pred = xgb_1.predict(X_val)
# cool_score = rmse_loss(y_pred, y_val)
# print(f"Feature Selection Only RMSE: {cool_score}")

## Big Tuna

In [14]:
import optuna
from sklearn.model_selection import cross_val_score

In [15]:
def objective(trial):
    params = {
        "objective": "reg:squarederror",
        "eval_metric": "rmse",
        "tree_method": "gpu_hist",
        "predictor": "gpu_predictor",
        "learning_rate": trial.suggest_float("learning_rate", 0.03, 0.1, step=0.01),
        "max_depth": trial.suggest_int("max_depth", 5, 20),
        "subsample": trial.suggest_float("subsample", 0.6, 1.0, step=0.1),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0, step=0.1),
        "max_bin": trial.suggest_int("max_bin", 256, 2048),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 10),
        "gamma": trial.suggest_float("gamma", 0, 5),
        "lambda": trial.suggest_float("lambda", 1e-3, 10.0, log=True),
        "alpha": trial.suggest_float("alpha", 1e-3, 10.0, log=True),
        "grow_policy": trial.suggest_categorical("grow_policy", ["depthwise", "lossguide"]),
        "random_state": 4
    }
    
    model = xgb.XGBRegressor(**params)
    score = cross_val_score(model, X, y, cv=2, scoring=rmse).mean()
    return np.abs(score)

In [16]:
study = optuna.create_study(direction='minimize',
                            sampler = optuna.samplers.RandomSampler(seed=42),
                            study_name = "BIG BLUE FIN TUNA!!")

[I 2025-04-26 16:54:37,849] A new study created in memory with name: BIG BLUE FIN TUNA!!

In [17]:
%%time
study.optimize(objective, n_trials=100, show_progress_bar=True)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2025-04-26 16:57:45,656] Trial 0 finished with value: 13.570135732102141 and parameters: {'learning_rate': 0.05, 'max_depth': 20, 'subsample': 0.9, 'colsample_bytree': 0.8, 'max_bin': 535, 'min_child_weight': 2, 'gamma': 0.2904180608409973, 'lambda': 2.9154431891537547, 'alpha': 0.2537815508265665, 'grow_policy': 'depthwise'}. Best is trial 0 with value: 13.570135732102141.
[I 2025-04-26 16:59:14,998] Trial 1 finished with value: 13.693833692680606 and parameters: {'learning_rate': 0.1, 'max_depth': 18, 'subsample': 0.7, 'colsample_bytree': 0.6, 'max_bin': 584, 'min_child_weight': 4, 'gamma': 2.6237821581611893, 'lambda': 0.05342937261279776, 'alpha': 0.014618962793704957, 'grow_policy': 'depthwise'}. Best is trial 0 with value: 13.570135732102141.
[I 2025-04-26 16:59:53,061] Trial 2 finished with value: 13.115315805676275 and parameters: {'learning_rate': 0.05, 'max_depth': 10, 'subsample': 0.8, 'colsample_bytree': 0.9, 'max_bin': 614, 'min_child_weight': 6, 'gamma': 2.9620728443102124, 'lambda': 0.0015339162591163618, 'alpha': 0.26926469100861794, 'grow_policy': 'depthwise'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 17:04:15,199] Trial 3 finished with value: 13.438540499921068 and parameters: {'learning_rate': 0.1, 'max_depth': 20, 'subsample': 1.0, 'colsample_bytree': 0.7, 'max_bin': 431, 'min_child_weight': 7, 'gamma': 2.2007624686980067, 'lambda': 0.003077180271250686, 'alpha': 0.09565499215943825, 'grow_policy': 'lossguide'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 17:05:45,046] Trial 4 finished with value: 13.314100473076444 and parameters: {'learning_rate': 0.05, 'max_depth': 15, 'subsample': 0.7, 'colsample_bytree': 0.8, 'max_bin': 1236, 'min_child_weight': 2, 'gamma': 4.847923138822793, 'lambda': 1.2604664585649468, 'alpha': 5.727904470799623, 'grow_policy': 'depthwise'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 17:06:17,337] Trial 5 finished with value: 13.146999698412511 and parameters: {'learning_rate': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bytree': 0.6, 'max_bin': 839, 'min_child_weight': 4, 'gamma': 1.3567451588694794, 'lambda': 2.0651425578959257, 'alpha': 0.026730883107816707, 'grow_policy': 'lossguide'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 17:13:53,313] Trial 6 finished with value: 13.517537935629914 and parameters: {'learning_rate': 0.04, 'max_depth': 17, 'subsample': 0.6, 'colsample_bytree': 1.0, 'max_bin': 1640, 'min_child_weight': 2, 'gamma': 0.027610585618011996, 'lambda': 1.8274508859816028, 'alpha': 0.6720930050156113, 'grow_policy': 'lossguide'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 17:14:36,159] Trial 7 finished with value: 13.203098203038031 and parameters: {'learning_rate': 0.03, 'max_depth': 10, 'subsample': 0.6, 'colsample_bytree': 1.0, 'max_bin': 1373, 'min_child_weight': 4, 'gamma': 0.3177917514301182, 'lambda': 0.017535949529764425, 'alpha': 0.01998634077852888, 'grow_policy': 'depthwise'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 17:15:20,284] Trial 8 finished with value: 13.517017658120956 and parameters: {'learning_rate': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bytree': 0.9, 'max_bin': 1620, 'min_child_weight': 6, 'gamma': 3.854835899772805, 'lambda': 0.09444574254983566, 'alpha': 0.12329098365270515, 'grow_policy': 'depthwise'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 17:15:51,504] Trial 9 finished with value: 13.23399811007035 and parameters: {'learning_rate': 0.03, 'max_depth': 5, 'subsample': 0.9, 'colsample_bytree': 0.7, 'max_bin': 1167, 'min_child_weight': 10, 'gamma': 1.2464611457443748, 'lambda': 0.04380580767905655, 'alpha': 1.0524574681335637, 'grow_policy': 'depthwise'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 17:16:28,207] Trial 10 finished with value: 13.133027741796418 and parameters: {'learning_rate': 0.05, 'max_depth': 7, 'subsample': 1.0, 'colsample_bytree': 1.0, 'max_bin': 1391, 'min_child_weight': 9, 'gamma': 4.018360384495573, 'lambda': 0.005575453980775369, 'alpha': 3.7173717478250508, 'grow_policy': 'lossguide'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 17:17:04,261] Trial 11 finished with value: 13.29221785382445 and parameters: {'learning_rate': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bytree': 0.7, 'max_bin': 1021, 'min_child_weight': 9, 'gamma': 4.303652916281717, 'lambda': 0.001066125968943389, 'alpha': 0.11040511903162252, 'grow_policy': 'depthwise'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 17:17:59,914] Trial 12 finished with value: 13.209408798373556 and parameters: {'learning_rate': 0.03, 'max_depth': 10, 'subsample': 1.0, 'colsample_bytree': 0.7, 'max_bin': 1186, 'min_child_weight': 8, 'gamma': 1.81814801189647, 'lambda': 7.711312991331111, 'alpha': 7.076022085822011, 'grow_policy': 'lossguide'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 17:18:45,461] Trial 13 finished with value: 13.17775975004377 and parameters: {'learning_rate': 0.05, 'max_depth': 9, 'subsample': 0.6, 'colsample_bytree': 0.9, 'max_bin': 1157, 'min_child_weight': 1, 'gamma': 1.3932323211830573, 'lambda': 4.295992790539128, 'alpha': 0.009083381663660588, 'grow_policy': 'lossguide'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 17:19:17,066] Trial 14 finished with value: 13.190555016652421 and parameters: {'learning_rate': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bytree': 0.9, 'max_bin': 682, 'min_child_weight': 8, 'gamma': 1.838915663596266, 'lambda': 0.3382387201936217, 'alpha': 0.3420730367009226, 'grow_policy': 'depthwise'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 17:19:52,432] Trial 15 finished with value: 13.228864069976016 and parameters: {'learning_rate': 0.09, 'max_depth': 10, 'subsample': 0.6, 'colsample_bytree': 0.6, 'max_bin': 1315, 'min_child_weight': 7, 'gamma': 0.08293914463928076, 'lambda': 0.11178209200698727, 'alpha': 0.008053471030316102, 'grow_policy': 'depthwise'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 17:20:53,030] Trial 16 finished with value: 13.23235797852751 and parameters: {'learning_rate': 0.08, 'max_depth': 11, 'subsample': 1.0, 'colsample_bytree': 0.6, 'max_bin': 867, 'min_child_weight': 2, 'gamma': 4.623468091392814, 'lambda': 3.2311521854410987, 'alpha': 0.01075886630676792, 'grow_policy': 'lossguide'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 17:22:42,175] Trial 17 finished with value: 13.1868077720657 and parameters: {'learning_rate': 0.07, 'max_depth': 13, 'subsample': 0.7, 'colsample_bytree': 0.6, 'max_bin': 1864, 'min_child_weight': 10, 'gamma': 3.16550728636634, 'lambda': 0.022704877557909234, 'alpha': 0.024936660834465198, 'grow_policy': 'lossguide'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 17:23:48,595] Trial 18 finished with value: 13.441788784369262 and parameters: {'learning_rate': 0.1, 'max_depth': 17, 'subsample': 0.9, 'colsample_bytree': 0.6, 'max_bin': 545, 'min_child_weight': 9, 'gamma': 3.0321452982979498, 'lambda': 0.0010883991813938126, 'alpha': 0.002546162816127691, 'grow_policy': 'depthwise'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 17:25:31,867] Trial 19 finished with value: 13.120811505472805 and parameters: {'learning_rate': 0.04, 'max_depth': 13, 'subsample': 0.9, 'colsample_bytree': 0.9, 'max_bin': 658, 'min_child_weight': 8, 'gamma': 1.1862454374840004, 'lambda': 0.020026211229345316, 'alpha': 0.9682012086882473, 'grow_policy': 'lossguide'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 17:27:23,035] Trial 20 finished with value: 13.491061921699949 and parameters: {'learning_rate': 0.08, 'max_depth': 14, 'subsample': 0.6, 'colsample_bytree': 0.7, 'max_bin': 731, 'min_child_weight': 3, 'gamma': 4.865052773762228, 'lambda': 0.03735862630812754, 'alpha': 3.6998679204890905, 'grow_policy': 'lossguide'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 17:30:12,081] Trial 21 finished with value: 13.314204620778888 and parameters: {'learning_rate': 0.07, 'max_depth': 14, 'subsample': 0.8, 'colsample_bytree': 0.6, 'max_bin': 1551, 'min_child_weight': 3, 'gamma': 0.1215798321572692, 'lambda': 0.3818468247973969, 'alpha': 0.0051102567156543965, 'grow_policy': 'lossguide'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 17:30:56,726] Trial 22 finished with value: 13.280694147319458 and parameters: {'learning_rate': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bytree': 1.0, 'max_bin': 1023, 'min_child_weight': 10, 'gamma': 4.818099885446264, 'lambda': 2.5824850844906155, 'alpha': 0.015058980408366392, 'grow_policy': 'lossguide'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 17:31:33,758] Trial 23 finished with value: 13.143861929802224 and parameters: {'learning_rate': 0.05, 'max_depth': 7, 'subsample': 0.8, 'colsample_bytree': 1.0, 'max_bin': 1503, 'min_child_weight': 6, 'gamma': 0.4858824688538427, 'lambda': 0.2884223471687845, 'alpha': 9.12463288668991, 'grow_policy': 'lossguide'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 17:32:52,989] Trial 24 finished with value: 13.424946586054354 and parameters: {'learning_rate': 0.1, 'max_depth': 16, 'subsample': 0.9, 'colsample_bytree': 0.9, 'max_bin': 900, 'min_child_weight': 3, 'gamma': 4.046805777392568, 'lambda': 1.7396167422846986, 'alpha': 2.9396070097391505, 'grow_policy': 'depthwise'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 17:34:34,919] Trial 25 finished with value: 13.268890006903742 and parameters: {'learning_rate': 0.07, 'max_depth': 17, 'subsample': 0.9, 'colsample_bytree': 0.9, 'max_bin': 1682, 'min_child_weight': 9, 'gamma': 1.689975784257679, 'lambda': 0.03179302199939539, 'alpha': 0.002376444955386536, 'grow_policy': 'depthwise'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 17:36:08,472] Trial 26 finished with value: 13.35622005899835 and parameters: {'learning_rate': 0.06, 'max_depth': 13, 'subsample': 0.7, 'colsample_bytree': 0.8, 'max_bin': 310, 'min_child_weight': 1, 'gamma': 4.113002803298292, 'lambda': 0.027590690254397858, 'alpha': 0.003222864528968034, 'grow_policy': 'lossguide'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 17:37:11,368] Trial 27 finished with value: 13.14062672959641 and parameters: {'learning_rate': 0.04, 'max_depth': 14, 'subsample': 0.6, 'colsample_bytree': 0.6, 'max_bin': 1208, 'min_child_weight': 6, 'gamma': 3.187149507491033, 'lambda': 0.8023527304678846, 'alpha': 8.005866020696466, 'grow_policy': 'depthwise'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 17:37:45,303] Trial 28 finished with value: 13.13868241601243 and parameters: {'learning_rate': 0.09, 'max_depth': 9, 'subsample': 0.8, 'colsample_bytree': 0.6, 'max_bin': 301, 'min_child_weight': 10, 'gamma': 4.1799006025610295, 'lambda': 0.6079905434073399, 'alpha': 0.043232642103703305, 'grow_policy': 'depthwise'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 17:38:37,805] Trial 29 finished with value: 13.129954477281196 and parameters: {'learning_rate': 0.05, 'max_depth': 13, 'subsample': 0.9, 'colsample_bytree': 0.9, 'max_bin': 757, 'min_child_weight': 10, 'gamma': 3.6894845834788423, 'lambda': 0.1649742679984546, 'alpha': 0.2798227271704929, 'grow_policy': 'depthwise'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 17:43:15,355] Trial 30 finished with value: 13.33762424949111 and parameters: {'learning_rate': 0.05, 'max_depth': 17, 'subsample': 0.6, 'colsample_bytree': 0.6, 'max_bin': 338, 'min_child_weight': 1, 'gamma': 4.277302920055036, 'lambda': 0.6525765108342366, 'alpha': 0.07883068789768044, 'grow_policy': 'lossguide'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 17:43:51,603] Trial 31 finished with value: 13.124113843880458 and parameters: {'learning_rate': 0.06, 'max_depth': 7, 'subsample': 0.8, 'colsample_bytree': 0.7, 'max_bin': 1360, 'min_child_weight': 7, 'gamma': 0.2265200488602226, 'lambda': 0.0315101491238403, 'alpha': 0.3187422711813415, 'grow_policy': 'lossguide'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 17:44:21,788] Trial 32 finished with value: 13.14341039278577 and parameters: {'learning_rate': 0.08, 'max_depth': 7, 'subsample': 0.6, 'colsample_bytree': 0.9, 'max_bin': 303, 'min_child_weight': 6, 'gamma': 4.701151207124788, 'lambda': 0.20039953593612145, 'alpha': 0.035700944411057804, 'grow_policy': 'depthwise'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 18:00:33,127] Trial 33 finished with value: 13.656227091300707 and parameters: {'learning_rate': 0.07, 'max_depth': 20, 'subsample': 0.7, 'colsample_bytree': 1.0, 'max_bin': 1879, 'min_child_weight': 2, 'gamma': 0.3468065043758273, 'lambda': 0.0025299503921303707, 'alpha': 0.0011827346017839087, 'grow_policy': 'lossguide'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 18:01:13,758] Trial 34 finished with value: 13.174836773573771 and parameters: {'learning_rate': 0.03, 'max_depth': 10, 'subsample': 1.0, 'colsample_bytree': 0.6, 'max_bin': 1716, 'min_child_weight': 3, 'gamma': 0.5908241381082813, 'lambda': 0.6122780092275809, 'alpha': 0.3279226289997166, 'grow_policy': 'depthwise'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 18:01:54,363] Trial 35 finished with value: 13.244682227402606 and parameters: {'learning_rate': 0.09, 'max_depth': 9, 'subsample': 0.6, 'colsample_bytree': 0.9, 'max_bin': 1702, 'min_child_weight': 10, 'gamma': 2.0630883845571324, 'lambda': 0.030766092622690297, 'alpha': 1.2754159474033702, 'grow_policy': 'lossguide'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 18:02:30,876] Trial 36 finished with value: 13.210553891048288 and parameters: {'learning_rate': 0.09, 'max_depth': 11, 'subsample': 0.9, 'colsample_bytree': 0.9, 'max_bin': 440, 'min_child_weight': 10, 'gamma': 2.5262618622392856, 'lambda': 2.022226812842965, 'alpha': 0.019063314120324366, 'grow_policy': 'depthwise'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 18:09:44,619] Trial 37 finished with value: 13.164395670172429 and parameters: {'learning_rate': 0.03, 'max_depth': 19, 'subsample': 0.6, 'colsample_bytree': 0.7, 'max_bin': 1959, 'min_child_weight': 10, 'gamma': 2.8671894406164307, 'lambda': 0.3367819821522134, 'alpha': 0.06219881174029358, 'grow_policy': 'lossguide'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 18:11:03,011] Trial 38 finished with value: 13.365346739465991 and parameters: {'learning_rate': 0.08, 'max_depth': 17, 'subsample': 0.9, 'colsample_bytree': 0.9, 'max_bin': 419, 'min_child_weight': 5, 'gamma': 0.2877938000832214, 'lambda': 0.15780309954142968, 'alpha': 0.05836090333829237, 'grow_policy': 'depthwise'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 18:11:34,933] Trial 39 finished with value: 13.264868656984952 and parameters: {'learning_rate': 0.03, 'max_depth': 7, 'subsample': 0.9, 'colsample_bytree': 0.9, 'max_bin': 437, 'min_child_weight': 1, 'gamma': 3.5048456572955997, 'lambda': 0.0019545735860656967, 'alpha': 1.9383858782150505, 'grow_policy': 'depthwise'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 18:19:10,570] Trial 40 finished with value: 13.17510376685196 and parameters: {'learning_rate': 0.03, 'max_depth': 20, 'subsample': 0.7, 'colsample_bytree': 0.7, 'max_bin': 1713, 'min_child_weight': 10, 'gamma': 4.930005319114354, 'lambda': 1.0316033434719722, 'alpha': 0.03199177539819798, 'grow_policy': 'lossguide'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 18:20:17,382] Trial 41 finished with value: 13.322854100297729 and parameters: {'learning_rate': 0.07, 'max_depth': 11, 'subsample': 1.0, 'colsample_bytree': 0.6, 'max_bin': 1139, 'min_child_weight': 1, 'gamma': 2.3433032099706312, 'lambda': 0.001679627987843051, 'alpha': 0.0029872506553136487, 'grow_policy': 'lossguide'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 18:21:06,967] Trial 42 finished with value: 13.160394565727746 and parameters: {'learning_rate': 0.08, 'max_depth': 14, 'subsample': 1.0, 'colsample_bytree': 0.7, 'max_bin': 768, 'min_child_weight': 9, 'gamma': 1.117979192597263, 'lambda': 7.126727573532314, 'alpha': 0.0011184534120760477, 'grow_policy': 'depthwise'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 18:22:33,222] Trial 43 finished with value: 13.298317108690004 and parameters: {'learning_rate': 0.1, 'max_depth': 13, 'subsample': 1.0, 'colsample_bytree': 0.6, 'max_bin': 1249, 'min_child_weight': 10, 'gamma': 2.615489220850744, 'lambda': 0.3293021396342672, 'alpha': 0.6067290033535007, 'grow_policy': 'lossguide'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 18:27:44,279] Trial 44 finished with value: 13.36425439727433 and parameters: {'learning_rate': 0.07, 'max_depth': 19, 'subsample': 0.6, 'colsample_bytree': 0.7, 'max_bin': 1960, 'min_child_weight': 9, 'gamma': 2.278283763928565, 'lambda': 0.30236421525614154, 'alpha': 0.012868405331151606, 'grow_policy': 'lossguide'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 18:28:57,507] Trial 45 finished with value: 13.207126034645384 and parameters: {'learning_rate': 0.05, 'max_depth': 14, 'subsample': 0.6, 'colsample_bytree': 1.0, 'max_bin': 2024, 'min_child_weight': 7, 'gamma': 2.680481831720602, 'lambda': 0.017302564033031168, 'alpha': 1.7996169659044359, 'grow_policy': 'depthwise'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 18:33:47,901] Trial 46 finished with value: 13.424834806338023 and parameters: {'learning_rate': 0.1, 'max_depth': 18, 'subsample': 1.0, 'colsample_bytree': 0.9, 'max_bin': 1355, 'min_child_weight': 5, 'gamma': 4.663642416770067, 'lambda': 2.912430416261911, 'alpha': 0.0015166126720973767, 'grow_policy': 'lossguide'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 18:35:13,367] Trial 47 finished with value: 13.424969286189732 and parameters: {'learning_rate': 0.09, 'max_depth': 20, 'subsample': 0.6, 'colsample_bytree': 0.8, 'max_bin': 938, 'min_child_weight': 10, 'gamma': 4.210594615678543, 'lambda': 2.255873896214238, 'alpha': 0.07495017292334746, 'grow_policy': 'depthwise'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 18:43:53,137] Trial 48 finished with value: 13.534416131713096 and parameters: {'learning_rate': 0.03, 'max_depth': 18, 'subsample': 1.0, 'colsample_bytree': 1.0, 'max_bin': 2042, 'min_child_weight': 6, 'gamma': 3.8449370759025525, 'lambda': 6.0126084038369445, 'alpha': 2.503741931228843, 'grow_policy': 'lossguide'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 18:54:01,251] Trial 49 finished with value: 13.170171475686505 and parameters: {'learning_rate': 0.04, 'max_depth': 20, 'subsample': 0.9, 'colsample_bytree': 0.7, 'max_bin': 1460, 'min_child_weight': 7, 'gamma': 1.7908135901642024, 'lambda': 0.002845970334341385, 'alpha': 0.48561577077656753, 'grow_policy': 'lossguide'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 19:01:01,484] Trial 50 finished with value: 13.363224770489186 and parameters: {'learning_rate': 0.07, 'max_depth': 18, 'subsample': 0.8, 'colsample_bytree': 0.8, 'max_bin': 1827, 'min_child_weight': 5, 'gamma': 0.6700761422532037, 'lambda': 0.0013035590385085064, 'alpha': 1.0484531351650956, 'grow_policy': 'lossguide'}. Best is trial 2 with value: 13.115315805676275.
[I 2025-04-26 19:01:37,183] Trial 51 finished with value: 13.147822066777717 and parameters: {'learning_rate': 0.04, 'max_depth': 7, 'subsample': 0.6, 'colsample_bytree': 0.7, 'max_bin': 1313, 'min_child_weight': 4, 'gamma': 2.1873746101186455, 'lambda': 4.136516661602461, 'alpha': 0.02471848607234944, 'grow_policy': 'lossguide'}. Best is trial 2 with value: 13.115315805676275.

In [18]:
best_params = study.best_params
print(f'Best Trial Params: {best_params}')

print(f'Best Trial Value: {study.best_trial.value}')

Best Trial Params: {'learning_rate': 0.05, 'max_depth': 10, 'subsample': 0.8, 'colsample_bytree': 0.9, 'max_bin': 614, 'min_child_weight': 6, 'gamma': 2.9620728443102124, 'lambda': 0.0015339162591163618, 'alpha': 0.26926469100861794, 'grow_policy': 'depthwise'}
Best Trial Value: 13.115315805676275

In [19]:
optuna.visualization.plot_optimization_history(study)

In [20]:
optuna.visualization.plot_parallel_coordinate(study)

In [21]:
optuna.visualization.plot_slice(study, params = ['max_depth', 'gamma', 'min_child_weight', 'alpha', 'subsample'])

In [22]:
optuna.visualization.plot_param_importances(study)

# Submission

In [23]:
best_model = xgb.XGBRegressor(params=best_params, 
                              objective="reg:squarederror",
                              eval_metric= "rmse",
                              tree_method= "gpu_hist",
                              predictor="gpu_predictor").fit(X, y)

In [24]:
df_test = pd.read_csv("/kaggle/input/playground-series-s5e4/test.csv")
df_test[df_test.select_dtypes(include='object').columns] = df_test[df_test.select_dtypes(include='object').columns].astype('category')

In [25]:
# df_test_clean = clean_test_set(df_test)
df_test_cool = make_cool_features(df_test)

In [26]:
cols_to_drop = [col for col in df_test_cool.columns if '20' in col or '100' in col]
df_test_cool = df_test_cool.drop(columns=cols_to_drop)

In [27]:
submission = pd.read_csv("/kaggle/input/playground-series-s5e4/sample_submission.csv")
submission["Listening_Time_minutes"] = best_model.predict(df_test_cool)

In [28]:
submission.to_csv("submission.csv", index=False)
submission.head()

       id  Listening_Time_minutes
0  750000               50.568573
1  750001               47.268456
2  750002               53.185898
3  750003               50.527401
4  750004               44.391212